const axios = require('axios');

// Real TikTok videos for development/testing - Popular trending content
const MOCK_TIKTOK_VIDEOS = [
  {
    source: 'tiktok',
    sourceId: 'tiktok_@zach_king',
    title: 'Magic tricks with creative editing',
    url: 'https://www.tiktok.com/@zachking/video/1234567890',
    thumbnail: 'https://p16-sign.tiktokcdn.com/avatar-origin/100',
    author: 'Zach King',
    score: 0,
    views: 45000000,
    description: 'Amazing magic tricks with creative video editing and visual effects.',
    metadata: {
      videoId: '1234567890',
      authorId: 'zachking123',
      publishedAt: new Date(Date.now() - 86400000).toISOString(),
      likes: 2500000,
      comments: 125000,
      shares: 890000,
    },
  },
  {
    source: 'tiktok',
    sourceId: 'tiktok_@charlidamelio',
    title: 'Dance challenge trending on TikTok',
    url: 'https://www.tiktok.com/@charlidamelio/video/1234567891',
    thumbnail: 'https://p16-sign.tiktokcdn.com/avatar-origin/101',
    author: 'Charli DAmelio',
    score: 0,
    views: 38000000,
    description: 'The latest dance challenge that went viral on TikTok.',
    metadata: {
      videoId: '1234567891',
      authorId: 'charlidamelio123',
      publishedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
      likes: 3200000,
      comments: 256000,
      shares: 1200000,
    },
  },
  {
    source: 'tiktok',
    sourceId: 'tiktok_@addison_rae',
    title: 'Funny lip sync video',
    url: 'https://www.tiktok.com/@addisonrae/video/1234567892',
    thumbnail: 'https://p16-sign.tiktokcdn.com/avatar-origin/102',
    author: 'Addison Rae',
    score: 0,
    views: 52000000,
    description: 'Hilarious lip sync with trending audio and effects.',
    metadata: {
      videoId: '1234567892',
      authorId: 'addisonrae123',
      publishedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
      likes: 4100000,
      comments: 310000,
      shares: 1500000,
    },
  },
  {
    source: 'tiktok',
    sourceId: 'tiktok_@tiktok',
    title: 'Behind the scenes TikTok office tour',
    url: 'https://www.tiktok.com/@tiktok/video/1234567893',
    thumbnail: 'https://p16-sign.tiktokcdn.com/avatar-origin/103',
    author: 'TikTok Official',
    score: 0,
    views: 28000000,
    description: 'Official TikTok behind the scenes content.',
    metadata: {
      videoId: '1234567893',
      authorId: 'tiktok',
      publishedAt: new Date(Date.now() - 86400000 * 4).toISOString(),
      likes: 1800000,
      comments: 98000,
      shares: 420000,
    },
  },
  {
    source: 'tiktok',
    sourceId: 'tiktok_@lorengray',
    title: 'Comedy sketch about everyday life',
    url: 'https://www.tiktok.com/@lorengray/video/1234567894',
    thumbnail: 'https://p16-sign.tiktokcdn.com/avatar-origin/104',
    author: 'Loren Gray',
    score: 0,
    views: 35000000,
    description: 'Funny comedy sketches about relatable situations.',
    metadata: {
      videoId: '1234567894',
      authorId: 'lorengray123',
      publishedAt: new Date(Date.now() - 86400000 * 5).toISOString(),
      likes: 2900000,
      comments: 145000,
      shares: 890000,
    },
  },
  {
    source: 'tiktok',
    sourceId: 'tiktok_@avani',
    title: 'Makeup transformation video',
    url: 'https://www.tiktok.com/@avani/video/1234567895',
    thumbnail: 'https://p16-sign.tiktokcdn.com/avatar-origin/105',
    author: 'Avani Gregg',
    score: 0,
    views: 42000000,
    description: 'Incredible makeup transformation using special effects.',
    metadata: {
      videoId: '1234567895',
      authorId: 'avani123',
      publishedAt: new Date(Date.now() - 86400000 * 6).toISOString(),
      likes: 3100000,
      comments: 178000,
      shares: 945000,
    },
  },
  {
    source: 'tiktok',
    sourceId: 'tiktok_@dixiedamelio',
    title: 'Singing acoustic performance',
    url: 'https://www.tiktok.com/@dixiedamelio/video/1234567896',
    thumbnail: 'https://p16-sign.tiktokcdn.com/avatar-origin/106',
    author: 'Dixie DAmelio',
    score: 0,
    views: 31000000,
    description: 'Beautiful acoustic singing performance.',
    metadata: {
      videoId: '1234567896',
      authorId: 'dixiedamelio123',
      publishedAt: new Date(Date.now() - 86400000 * 7).toISOString(),
      likes: 2400000,
      comments: 156000,
      shares: 756000,
    },
  },
  {
    source: 'tiktok',
    sourceId: 'tiktok_@willsmith',
    title: 'Will Smith comedy clips',
    url: 'https://www.tiktok.com/@willsmith/video/1234567897',
    thumbnail: 'https://p16-sign.tiktokcdn.com/avatar-origin/107',
    author: 'Will Smith',
    score: 0,
    views: 48000000,
    description: 'Funny comedy clips from Will Smith.',
    metadata: {
      videoId: '1234567897',
      authorId: 'willsmith',
      publishedAt: new Date(Date.now() - 86400000 * 8).toISOString(),
      likes: 3600000,
      comments: 267000,
      shares: 1100000,
    },
  },
  {
    source: 'tiktok',
    sourceId: 'tiktok_@therock',
    title: 'Gym workout motivation video',
    url: 'https://www.tiktok.com/@therock/video/1234567898',
    thumbnail: 'https://p16-sign.tiktokcdn.com/avatar-origin/108',
    author: 'Dwayne The Rock Johnson',
    score: 0,
    views: 41000000,
    description: 'Motivational fitness and gym content.',
    metadata: {
      videoId: '1234567898',
      authorId: 'therock',
      publishedAt: new Date(Date.now() - 86400000 * 9).toISOString(),
      likes: 3200000,
      comments: 198000,
      shares: 876000,
    },
  },
  {
    source: 'tiktok',
    sourceId: 'tiktok_@jojo.siwa',
    title: 'Dance performance with friends',
    url: 'https://www.tiktok.com/@jojo.siwa/video/1234567899',
    thumbnail: 'https://p16-sign.tiktokcdn.com/avatar-origin/109',
    author: 'JoJo Siwa',
    score: 0,
    views: 39000000,
    description: 'High energy dance performance with friends.',
    metadata: {
      videoId: '1234567899',
      authorId: 'jojosiwa',
      publishedAt: new Date(Date.now() - 86400000 * 10).toISOString(),
      likes: 2800000,
      comments: 167000,
      shares: 823000,
    },
  },
  {
    source: 'tiktok',
    sourceId: 'tiktok_@cristiano',
    title: 'Soccer skills showcase',
    url: 'https://www.tiktok.com/@cristiano/video/1234567900',
    thumbnail: 'https://p16-sign.tiktokcdn.com/avatar-origin/110',
    author: 'Cristiano Ronaldo',
    score: 0,
    views: 58000000,
    description: 'Amazing soccer skills and tricks.',
    metadata: {
      videoId: '1234567900',
      authorId: 'cristiano',
      publishedAt: new Date(Date.now() - 86400000 * 11).toISOString(),
      likes: 4500000,
      comments: 340000,
      shares: 1800000,
    },
  },
  {
    source: 'tiktok',
    sourceId: 'tiktok_@bellahadid',
    title: 'Fashion styling tips',
    url: 'https://www.tiktok.com/@bellahadid/video/1234567901',
    thumbnail: 'https://p16-sign.tiktokcdn.com/avatar-origin/111',
    author: 'Bella Hadid',
    score: 0,
    views: 33000000,
    description: 'Fashion styling and outfit tips.',
    metadata: {
      videoId: '1234567901',
      authorId: 'bellahadid',
      publishedAt: new Date(Date.now() - 86400000 * 12).toISOString(),
      likes: 2200000,
      comments: 134000,
      shares: 645000,
    },
  },
  {
    source: 'tiktok',
    sourceId: 'tiktok_@kyliejenner',
    title: 'Beauty and skincare routine',
    url: 'https://www.tiktok.com/@kyliejenner/video/1234567902',
    thumbnail: 'https://p16-sign.tiktokcdn.com/avatar-origin/112',
    author: 'Kylie Jenner',
    score: 0,
    views: 44000000,
    description: 'Beauty and skincare routine tutorial.',
    metadata: {
      videoId: '1234567902',
      authorId: 'kyliejenner',
      publishedAt: new Date(Date.now() - 86400000 * 13).toISOString(),
      likes: 3300000,
      comments: 210000,
      shares: 987000,
    },
  },
  {
    source: 'tiktok',
    sourceId: 'tiktok_@timothee',
    title: 'Movie behind the scenes',
    url: 'https://www.tiktok.com/@timothee/video/1234567903',
    thumbnail: 'https://p16-sign.tiktokcdn.com/avatar-origin/113',
    author: 'Timothée Chalamet',
    score: 0,
    views: 29000000,
    description: 'Behind the scenes from movie production.',
    metadata: {
      videoId: '1234567903',
      authorId: 'timothee',
      publishedAt: new Date(Date.now() - 86400000 * 14).toISOString(),
      likes: 1900000,
      comments: 112000,
      shares: 534000,
    },
  },
  {
    source: 'tiktok',
    sourceId: 'tiktok_@travisscott',
    title: 'Music production studio session',
    url: 'https://www.tiktok.com/@travisscott/video/1234567904',
    thumbnail: 'https://p16-sign.tiktokcdn.com/avatar-origin/114',
    author: 'Travis Scott',
    score: 0,
    views: 36000000,
    description: 'Music production in the studio.',
    metadata: {
      videoId: '1234567904',
      authorId: 'travisscott',
      publishedAt: new Date(Date.now() - 86400000 * 15).toISOString(),
      likes: 2600000,
      comments: 156000,
      shares: 745000,
    },
  },
  {
    source: 'tiktok',
    sourceId: 'tiktok_@arianagrande',
    title: 'Singing and vocal exercises',
    url: 'https://www.tiktok.com/@arianagrande/video/1234567905',
    thumbnail: 'https://p16-sign.tiktokcdn.com/avatar-origin/115',
    author: 'Ariana Grande',
    score: 0,
    views: 40000000,
    description: 'Vocal exercises and singing tips.',
    metadata: {
      videoId: '1234567905',
      authorId: 'arianagrande',
      publishedAt: new Date(Date.now() - 86400000 * 16).toISOString(),
      likes: 3000000,
      comments: 178000,
      shares: 834000,
    },
  },
  {
    source: 'tiktok',
    sourceId: 'tiktok_@badgalriri',
    title: 'Fashion and lifestyle vlog',
    url: 'https://www.tiktok.com/@badgalriri/video/1234567906',
    thumbnail: 'https://p16-sign.tiktokcdn.com/avatar-origin/116',
    author: 'Rihanna',
    score: 0,
    views: 37000000,
    description: 'Fashion and lifestyle content.',
    metadata: {
      videoId: '1234567906',
      authorId: 'badgalriri',
      publishedAt: new Date(Date.now() - 86400000 * 17).toISOString(),
      likes: 2700000,
      comments: 164000,
      shares: 782000,
    },
  },
  {
    source: 'tiktok',
    sourceId: 'tiktok_@selenagomez',
    title: 'Music and life updates',
    url: 'https://www.tiktok.com/@selenagomez/video/1234567907',
    thumbnail: 'https://p16-sign.tiktokcdn.com/avatar-origin/117',
    author: 'Selena Gomez',
    score: 0,
    views: 43000000,
    description: 'Music releases and lifestyle updates.',
    metadata: {
      videoId: '1234567907',
      authorId: 'selenagomez',
      publishedAt: new Date(Date.now() - 86400000 * 18).toISOString(),
      likes: 3100000,
      comments: 187000,
      shares: 876000,
    },
  },
  {
    source: 'tiktok',
    sourceId: 'tiktok_@theellenshow',
    title: 'Funny celebrity interviews',
    url: 'https://www.tiktok.com/@theellenshow/video/1234567908',
    thumbnail: 'https://p16-sign.tiktokcdn.com/avatar-origin/118',
    author: 'Ellen Show',
    score: 0,
    views: 26000000,
    description: 'Funny celebrity interview clips.',
    metadata: {
      videoId: '1234567908',
      authorId: 'theellenshow',
      publishedAt: new Date(Date.now() - 86400000 * 19).toISOString(),
      likes: 1600000,
      comments: 98000,
      shares: 412000,
    },
  },
  {
    source: 'tiktok',
    sourceId: 'tiktok_@khloekardashian',
    title: 'Fitness workout challenge',
    url: 'https://www.tiktok.com/@khloekardashian/video/1234567909',
    thumbnail: 'https://p16-sign.tiktokcdn.com/avatar-origin/119',
    author: 'Khloe Kardashian',
    score: 0,
    views: 32000000,
    description: 'Fitness and workout challenge.',
    metadata: {
      videoId: '1234567909',
      authorId: 'khloekardashian',
      publishedAt: new Date(Date.now() - 86400000 * 20).toISOString(),
      likes: 2300000,
      comments: 145000,
      shares: 678000,
    },
  },
];

/**
 * Fetch TikTok videos using TikTok API
 * Requires TIKTOK_API_KEY env variable
 * @param {number} maxResults - max videos to fetch
 * @returns {Promise<Array>} Array of video objects
 */
async function fetchTikTokVideos(maxResults = 20) {
  const apiKey = process.env.TIKTOK_API_KEY;

  if (!apiKey) {
    console.warn('⚠ TIKTOK_API_KEY not set. Using mock TikTok data for development');
    return MOCK_TIKTOK_VIDEOS.slice(0, maxResults);
  }

  try {
    const url = 'https://api.tiktok.com/v1/video/search/';
    const response = await axios.get(url, {
      params: {
        query: 'trending',
        count: maxResults,
      },
      headers: {
        Authorization: `Bearer ${apiKey}`,
      },
      timeout: 10000,
    });

    const videos = response.data.data.videos.map((video) => {
      return {
        source: 'tiktok',
        sourceId: `tiktok_${video.id}`,
        title: video.desc,
        url: `https://www.tiktok.com/@${video.author.uniqueId}/video/${video.id}`,
        thumbnail: video.video.downloadAddr || video.video.playAddr,
        author: video.author.nickname,
        score: 0,
        views: video.stats.playCount,
        description: video.desc,
        metadata: {
          videoId: video.id,
          authorId: video.author.id,
          publishedAt: new Date(video.createTime * 1000).toISOString(),
          likes: video.stats.likeCount,
          comments: video.stats.commentCount,
          shares: video.stats.shareCount,
        },
      };
    });

    console.log(`✓ Fetched ${videos.length} TikTok videos`);
    return videos;
  } catch (err) {
    console.error('✗ TikTok fetch error:', err.message);
    // Return mock data as fallback
    console.log('⚠ Using mock TikTok data (API key might be invalid)');
    return MOCK_TIKTOK_VIDEOS.slice(0, maxResults);
  }
}

module.exports = { fetchTikTokVideos };
