const axios = require('axios');

// Real YouTube Shorts for development/testing - Popular short-form videos
const MOCK_YOUTUBE_SHORTS = [
  {
    source: 'youtube',
    sourceId: 'youtube_dQw4w9WgXcQ',
    title: 'Most Viewed YouTube Video Ever',
    url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    thumbnail: 'https://i.ytimg.com/vi/dQw4w9WgXcQ/default.jpg',
    author: 'Rick Astley',
    score: 0,
    views: 1424000000,
    description: 'The most iconic video on YouTube.',
    metadata: {
      videoId: 'dQw4w9WgXcQ',
      channelId: 'UCuAXFkgsw1L7xaCfnd5J5KQ',
      publishedAt: new Date(Date.now() - 86400000).toISOString(),
    },
  },
  {
    source: 'youtube',
    sourceId: 'youtube_9bZkp7q19f0',
    title: 'PSY - GANGNAM STYLE',
    url: 'https://www.youtube.com/watch?v=9bZkp7q19f0',
    thumbnail: 'https://i.ytimg.com/vi/9bZkp7q19f0/default.jpg',
    author: 'officialpsy',
    score: 0,
    views: 4629000000,
    description: 'Gangnam Style Dance',
    metadata: {
      videoId: '9bZkp7q19f0',
      channelId: 'UCrDkAvwXgD9FNucMzeIElFg',
      publishedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    },
  },
  {
    source: 'youtube',
    sourceId: 'youtube_jNQXAC9IVRw',
    title: 'Me at the zoo',
    url: 'https://www.youtube.com/watch?v=jNQXAC9IVRw',
    thumbnail: 'https://i.ytimg.com/vi/jNQXAC9IVRw/default.jpg',
    author: 'jawed',
    score: 0,
    views: 250000000,
    description: 'The first YouTube video ever uploaded.',
    metadata: {
      videoId: 'jNQXAC9IVRw',
      channelId: 'UCkRfArvrzheW2E7b6SVV6vQ',
      publishedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    },
  },
  {
    source: 'youtube',
    sourceId: 'youtube_kffacxfA7g4',
    title: 'Baby - Justin Bieber',
    url: 'https://www.youtube.com/watch?v=kffacxfA7g4',
    thumbnail: 'https://i.ytimg.com/vi/kffacxfA7g4/default.jpg',
    author: 'JustinBieberVEVO',
    score: 0,
    views: 3250000000,
    description: 'Official video for Baby by Justin Bieber',
    metadata: {
      videoId: 'kffacxfA7g4',
      channelId: 'UCIcHI2oV-_7UrrC3yALlppw',
      publishedAt: new Date(Date.now() - 86400000 * 4).toISOString(),
    },
  },
  {
    source: 'youtube',
    sourceId: 'youtube_OPf0YbXqDm0',
    title: 'YouTube Rewind 2018',
    url: 'https://www.youtube.com/watch?v=OPf0YbXqDm0',
    thumbnail: 'https://i.ytimg.com/vi/OPf0YbXqDm0/default.jpg',
    author: 'YouTube Spotlight',
    score: 0,
    views: 230000000,
    description: 'A look back at 2018 on YouTube',
    metadata: {
      videoId: 'OPf0YbXqDm0',
      channelId: 'UCkRfArvrzheW2E7b6SVV6vQ',
      publishedAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    },
  },
  {
    source: 'youtube',
    sourceId: 'youtube_YQHsXMglC9A',
    title: 'Despacito - Luis Fonsi ft. Daddy Yankee',
    url: 'https://www.youtube.com/watch?v=YQHsXMglC9A',
    thumbnail: 'https://i.ytimg.com/vi/YQHsXMglC9A/default.jpg',
    author: 'Luis Fonsi',
    score: 0,
    views: 8100000000,
    description: 'The biggest song in the world',
    metadata: {
      videoId: 'YQHsXMglC9A',
      channelId: 'UCpDkYy1ZrVpVHFLkr0jMlLg',
      publishedAt: new Date(Date.now() - 86400000 * 6).toISOString(),
    },
  },
  {
    source: 'youtube',
    sourceId: 'youtube_5qap5aO4i9A',
    title: 'Shape of You - Ed Sheeran',
    url: 'https://www.youtube.com/watch?v=5qap5aO4i9A',
    thumbnail: 'https://i.ytimg.com/vi/5qap5aO4i9A/default.jpg',
    author: 'Ed Sheeran',
    score: 0,
    views: 3500000000,
    description: 'Shape of You official video',
    metadata: {
      videoId: '5qap5aO4i9A',
      channelId: 'UCIcHI2oV-_7UrrC3yALlppw',
      publishedAt: new Date(Date.now() - 86400000 * 7).toISOString(),
    },
  },
  {
    source: 'youtube',
    sourceId: 'youtube_kJQP7kiw9Fk',
    title: 'Luis Fonsi, Daddy Yankee ft. Justin Bieber - Despacito (Remix)',
    url: 'https://www.youtube.com/watch?v=kJQP7kiw9Fk',
    thumbnail: 'https://i.ytimg.com/vi/kJQP7kiw9Fk/default.jpg',
    author: 'Luis Fonsi',
    score: 0,
    views: 5000000000,
    description: 'Despacito Remix',
    metadata: {
      videoId: 'kJQP7kiw9Fk',
      channelId: 'UCpDkYy1ZrVpVHFLkr0jMlLg',
      publishedAt: new Date(Date.now() - 86400000 * 8).toISOString(),
    },
  },
  {
    source: 'youtube',
    sourceId: 'youtube_RB-RcX5DS5A',
    title: 'Mark Ronson - Uptown Special ft. Bruno Mars',
    url: 'https://www.youtube.com/watch?v=RB-RcX5DS5A',
    thumbnail: 'https://i.ytimg.com/vi/RB-RcX5DS5A/default.jpg',
    author: 'Mark Ronson',
    score: 0,
    views: 1200000000,
    description: 'Uptown Special official video',
    metadata: {
      videoId: 'RB-RcX5DS5A',
      channelId: 'UCKsb2_wLC5oL_cBBZH5kZpg',
      publishedAt: new Date(Date.now() - 86400000 * 9).toISOString(),
    },
  },
  {
    source: 'youtube',
    sourceId: 'youtube_WZd_wSyFRXc',
    title: 'See You Again - Wiz Khalifa ft. Charlie Puth',
    url: 'https://www.youtube.com/watch?v=WZd_wSyFRXc',
    thumbnail: 'https://i.ytimg.com/vi/WZd_wSyFRXc/default.jpg',
    author: 'Wiz Khalifa',
    score: 0,
    views: 3300000000,
    description: 'See You Again music video',
    metadata: {
      videoId: 'WZd_wSyFRXc',
      channelId: 'UCG5fkEKqnXWh-BoCcn0yT8w',
      publishedAt: new Date(Date.now() - 86400000 * 10).toISOString(),
    },
  },
  {
    source: 'youtube',
    sourceId: 'youtube_aqz-KE-bpKQ',
    title: 'Uptown Funk - Mark Ronson ft. Bruno Mars',
    url: 'https://www.youtube.com/watch?v=aqz-KE-bpKQ',
    thumbnail: 'https://i.ytimg.com/vi/aqz-KE-bpKQ/default.jpg',
    author: 'Mark Ronson',
    score: 0,
    views: 1500000000,
    description: 'Uptown Funk music video',
    metadata: {
      videoId: 'aqz-KE-bpKQ',
      channelId: 'UCKsb2_wLC5oL_cBBZH5kZpg',
      publishedAt: new Date(Date.now() - 86400000 * 11).toISOString(),
    },
  },
  {
    source: 'youtube',
    sourceId: 'youtube_tYzMGcUty6s',
    title: 'Thinking Out Loud - Ed Sheeran',
    url: 'https://www.youtube.com/watch?v=tYzMGcUty6s',
    thumbnail: 'https://i.ytimg.com/vi/tYzMGcUty6s/default.jpg',
    author: 'Ed Sheeran',
    score: 0,
    views: 2800000000,
    description: 'Thinking Out Loud official video',
    metadata: {
      videoId: 'tYzMGcUty6s',
      channelId: 'UCIcHI2oV-_7UrrC3yALlppw',
      publishedAt: new Date(Date.now() - 86400000 * 12).toISOString(),
    },
  },
  {
    source: 'youtube',
    sourceId: 'youtube_e-IWRmpefzE',
    title: 'Blank Space - Taylor Swift',
    url: 'https://www.youtube.com/watch?v=e-IWRmpefzE',
    thumbnail: 'https://i.ytimg.com/vi/e-IWRmpefzE/default.jpg',
    author: 'Taylor Swift',
    score: 0,
    views: 3200000000,
    description: 'Blank Space music video',
    metadata: {
      videoId: 'e-IWRmpefzE',
      channelId: 'UCN-_mVCRsKpDiEPMt6CQoUQ',
      publishedAt: new Date(Date.now() - 86400000 * 13).toISOString(),
    },
  },
  {
    source: 'youtube',
    sourceId: 'youtube_nfs8NYg7yQM',
    title: 'Shake It Off - Taylor Swift',
    url: 'https://www.youtube.com/watch?v=nfs8NYg7yQM',
    thumbnail: 'https://i.ytimg.com/vi/nfs8NYg7yQM/default.jpg',
    author: 'Taylor Swift',
    score: 0,
    views: 3100000000,
    description: 'Shake It Off official video',
    metadata: {
      videoId: 'nfs8NYg7yQM',
      channelId: 'UCN-_mVCRsKpDiEPMt6CQoUQ',
      publishedAt: new Date(Date.now() - 86400000 * 14).toISOString(),
    },
  },
  {
    source: 'youtube',
    sourceId: 'youtube_3AtDnelULVo',
    title: 'Bad Guy - Billie Eilish',
    url: 'https://www.youtube.com/watch?v=3AtDnelULVo',
    thumbnail: 'https://i.ytimg.com/vi/3AtDnelULVo/default.jpg',
    author: 'Billie Eilish',
    score: 0,
    views: 850000000,
    description: 'Bad Guy official video',
    metadata: {
      videoId: '3AtDnelULVo',
      channelId: 'UCU8aL_V9d6d-2Tx3ng5OeJA',
      publishedAt: new Date(Date.now() - 86400000 * 15).toISOString(),
    },
  },
  {
    source: 'youtube',
    sourceId: 'youtube_CvBfHwUxHIg',
    title: 'Blinding Lights - The Weeknd',
    url: 'https://www.youtube.com/watch?v=CvBfHwUxHIg',
    thumbnail: 'https://i.ytimg.com/vi/CvBfHwUxHIg/default.jpg',
    author: 'The Weeknd',
    score: 0,
    views: 2100000000,
    description: 'Blinding Lights official video',
    metadata: {
      videoId: 'CvBfHwUxHIg',
      channelId: 'UCbDSqDu2qFG1i-Dsb3D1pzA',
      publishedAt: new Date(Date.now() - 86400000 * 16).toISOString(),
    },
  },
  {
    source: 'youtube',
    sourceId: 'youtube_Xo-ebPrzybY',
    title: 'As It Was - Harry Styles',
    url: 'https://www.youtube.com/watch?v=Xo-ebPrzybY',
    thumbnail: 'https://i.ytimg.com/vi/Xo-ebPrzybY/default.jpg',
    author: 'Harry Styles',
    score: 0,
    views: 1350000000,
    description: 'As It Was official video',
    metadata: {
      videoId: 'Xo-ebPrzybY',
      channelId: 'UCn7aJSnKD7eXrHrY-MYwc4g',
      publishedAt: new Date(Date.now() - 86400000 * 17).toISOString(),
    },
  },
  {
    source: 'youtube',
    sourceId: 'youtube_rvrZJ5C_Nwg',
    title: 'Levitating - Dua Lipa',
    url: 'https://www.youtube.com/watch?v=rvrZJ5C_Nwg',
    thumbnail: 'https://i.ytimg.com/vi/rvrZJ5C_Nwg/default.jpg',
    author: 'Dua Lipa',
    score: 0,
    views: 620000000,
    description: 'Levitating official video',
    metadata: {
      videoId: 'rvrZJ5C_Nwg',
      channelId: 'UCKyLVGJtHZlGYVfjyJx2mWA',
      publishedAt: new Date(Date.now() - 86400000 * 18).toISOString(),
    },
  },
  {
    source: 'youtube',
    sourceId: 'youtube_axrFVDqKGzI',
    title: 'Anti-Hero - Taylor Swift',
    url: 'https://www.youtube.com/watch?v=axrFVDqKGzI',
    thumbnail: 'https://i.ytimg.com/vi/axrFVDqKGzI/default.jpg',
    author: 'Taylor Swift',
    score: 0,
    views: 520000000,
    description: 'Anti-Hero music video',
    metadata: {
      videoId: 'axrFVDqKGzI',
      channelId: 'UCN-_mVCRsKpDiEPMt6CQoUQ',
      publishedAt: new Date(Date.now() - 86400000 * 19).toISOString(),
    },
  },
  {
    source: 'youtube',
    sourceId: 'youtube_VJKUvtFJ9n4',
    title: 'Flower - Jisoo',
    url: 'https://www.youtube.com/watch?v=VJKUvtFJ9n4',
    thumbnail: 'https://i.ytimg.com/vi/VJKUvtFJ9n4/default.jpg',
    author: 'JisooOfficial',
    score: 0,
    views: 280000000,
    description: 'Flower official music video',
    metadata: {
      videoId: 'VJKUvtFJ9n4',
      channelId: 'UC3BzYGRV0-KV5sO8hIxVWpw',
      publishedAt: new Date(Date.now() - 86400000 * 20).toISOString(),
    },
  },
  {
    source: 'youtube',
    sourceId: 'youtube_6nU6pn4OZ4s',
    title: 'Money - Pink Floyd',
    url: 'https://www.youtube.com/watch?v=6nU6pn4OZ4s',
    thumbnail: 'https://i.ytimg.com/vi/6nU6pn4OZ4s/default.jpg',
    author: 'Pink Floyd',
    score: 0,
    views: 380000000,
    description: 'Money official video',
    metadata: {
      videoId: '6nU6pn4OZ4s',
      channelId: 'UCzTqVSWqhHV4KpqPO0RhKkA',
      publishedAt: new Date(Date.now() - 86400000 * 21).toISOString(),
    },
  },
  {
    source: 'youtube',
    sourceId: 'youtube_5Z_nriudGyo',
    title: 'Bohemian Rhapsody - Queen',
    url: 'https://www.youtube.com/watch?v=5Z_nriudGyo',
    thumbnail: 'https://i.ytimg.com/vi/5Z_nriudGyo/default.jpg',
    author: 'Queen Official',
    score: 0,
    views: 920000000,
    description: 'Bohemian Rhapsody official video',
    metadata: {
      videoId: '5Z_nriudGyo',
      channelId: 'UCiMhD4jzUqG-IgPzUmmYZiQ',
      publishedAt: new Date(Date.now() - 86400000 * 22).toISOString(),
    },
  },
  {
    source: 'youtube',
    sourceId: 'youtube_GI6CfKcMhjw',
    title: 'Somebody to Love - Queen',
    url: 'https://www.youtube.com/watch?v=GI6CfKcMhjw',
    thumbnail: 'https://i.ytimg.com/vi/GI6CfKcMhjw/default.jpg',
    author: 'Queen Official',
    score: 0,
    views: 550000000,
    description: 'Somebody to Love music video',
    metadata: {
      videoId: 'GI6CfKcMhjw',
      channelId: 'UCiMhD4jzUqG-IgPzUmmYZiQ',
      publishedAt: new Date(Date.now() - 86400000 * 23).toISOString(),
    },
  },
  {
    source: 'youtube',
    sourceId: 'youtube_4dvnHZYwn0Q',
    title: 'Stairway to Heaven - Led Zeppelin',
    url: 'https://www.youtube.com/watch?v=4dvnHZYwn0Q',
    thumbnail: 'https://i.ytimg.com/vi/4dvnHZYwn0Q/default.jpg',
    author: 'Led Zeppelin',
    score: 0,
    views: 430000000,
    description: 'Stairway to Heaven official',
    metadata: {
      videoId: '4dvnHZYwn0Q',
      channelId: 'UCnbB1D_XnE6C94A6Sf-Y5MQ',
      publishedAt: new Date(Date.now() - 86400000 * 24).toISOString(),
    },
  },
  {
    source: 'youtube',
    sourceId: 'youtube_kTJloE6C9oI',
    title: 'Smells Like Teen Spirit - Nirvana',
    url: 'https://www.youtube.com/watch?v=kTJloE6C9oI',
    thumbnail: 'https://i.ytimg.com/vi/kTJloE6C9oI/default.jpg',
    author: 'Nirvana',
    score: 0,
    views: 780000000,
    description: 'Smells Like Teen Spirit music video',
    metadata: {
      videoId: 'kTJloE6C9oI',
      channelId: 'UC_U5_twzIK0yNQg_5s1d6_A',
      publishedAt: new Date(Date.now() - 86400000 * 25).toISOString(),
    },
  },
  {
    source: 'youtube',
    sourceId: 'youtube_W_HpDVBPT1Q',
    title: 'Sorry - Justin Bieber',
    url: 'https://www.youtube.com/watch?v=W_HpDVBPT1Q',
    thumbnail: 'https://i.ytimg.com/vi/W_HpDVBPT1Q/default.jpg',
    author: 'JustinBieberVEVO',
    score: 0,
    views: 2950000000,
    description: 'Sorry official video',
    metadata: {
      videoId: 'W_HpDVBPT1Q',
      channelId: 'UCIcHI2oV-_7UrrC3yALlppw',
      publishedAt: new Date(Date.now() - 86400000 * 26).toISOString(),
    },
  },
  {
    source: 'youtube',
    sourceId: 'youtube_7qKcJF4fOW0',
    title: 'Love The Way You Lie - Eminem ft. Rihanna',
    url: 'https://www.youtube.com/watch?v=7qKcJF4fOW0',
    thumbnail: 'https://i.ytimg.com/vi/7qKcJF4fOW0/default.jpg',
    author: 'Eminem',
    score: 0,
    views: 1580000000,
    description: 'Love The Way You Lie official video',
    metadata: {
      videoId: '7qKcJF4fOW0',
      channelId: 'UCToFCBVHQi5AEoqLDiB-_gw',
      publishedAt: new Date(Date.now() - 86400000 * 27).toISOString(),
    },
  },
  {
    source: 'youtube',
    sourceId: 'youtube_u8P_bKvgOFo',
    title: 'Perfect - Ed Sheeran',
    url: 'https://www.youtube.com/watch?v=u8P_bKvgOFo',
    thumbnail: 'https://i.ytimg.com/vi/u8P_bKvgOFo/default.jpg',
    author: 'Ed Sheeran',
    score: 0,
    views: 2750000000,
    description: 'Perfect official music video',
    metadata: {
      videoId: 'u8P_bKvgOFo',
      channelId: 'UCIcHI2oV-_7UrrC3yALlppw',
      publishedAt: new Date(Date.now() - 86400000 * 28).toISOString(),
    },
  },
  {
    source: 'youtube',
    sourceId: 'youtube_a_426RiwST8',
    title: 'Someone You Loved - Lewis Capaldi',
    url: 'https://www.youtube.com/watch?v=a_426RiwST8',
    thumbnail: 'https://i.ytimg.com/vi/a_426RiwST8/default.jpg',
    author: 'Lewis Capaldi',
    score: 0,
    views: 1200000000,
    description: 'Someone You Loved official video',
    metadata: {
      videoId: 'a_426RiwST8',
      channelId: 'UC2N3wbPsM0zx4W5i2DUOxxA',
      publishedAt: new Date(Date.now() - 86400000 * 29).toISOString(),
    },
  },
  {
    source: 'youtube',
    sourceId: 'youtube_e1kqxY2ooX4',
    title: 'Dynamite - BTS',
    url: 'https://www.youtube.com/watch?v=e1kqxY2ooX4',
    thumbnail: 'https://i.ytimg.com/vi/e1kqxY2ooX4/default.jpg',
    author: 'HYBE Labels',
    score: 0,
    views: 680000000,
    description: 'Dynamite official music video',
    metadata: {
      videoId: 'e1kqxY2ooX4',
      channelId: 'UCNkEqaq0DzcXF0LPrECDp9A',
      publishedAt: new Date(Date.now() - 86400000 * 30).toISOString(),
    },
  },
  {
    source: 'youtube',
    sourceId: 'youtube_HrPXaJnAHis',
    title: 'Butter - BTS',
    url: 'https://www.youtube.com/watch?v=HrPXaJnAHis',
    thumbnail: 'https://i.ytimg.com/vi/HrPXaJnAHis/default.jpg',
    author: 'HYBE Labels',
    score: 0,
    views: 590000000,
    description: 'Butter official music video',
    metadata: {
      videoId: 'HrPXaJnAHis',
      channelId: 'UCNkEqaq0DzcXF0LPrECDp9A',
      publishedAt: new Date(Date.now() - 86400000 * 31).toISOString(),
    },
  },
  {
    source: 'youtube',
    sourceId: 'youtube_pLmkqJYVDPM',
    title: 'Good as Hell - Lizzo',
    url: 'https://www.youtube.com/watch?v=pLmkqJYVDPM',
    thumbnail: 'https://i.ytimg.com/vi/pLmkqJYVDPM/default.jpg',
    author: 'Lizzo',
    score: 0,
    views: 450000000,
    description: 'Good as Hell official video',
    metadata: {
      videoId: 'pLmkqJYVDPM',
      channelId: 'UC5VGVCiNPuKnrqY_gkYN9Aw',
      publishedAt: new Date(Date.now() - 86400000 * 32).toISOString(),
    },
  },
  {
    source: 'youtube',
    sourceId: 'youtube_i0r4M9GDfA4',
    title: 'Peaches - Justin Bieber ft. Daniel Caesar & Giveon',
    url: 'https://www.youtube.com/watch?v=i0r4M9GDfA4',
    thumbnail: 'https://i.ytimg.com/vi/i0r4M9GDfA4/default.jpg',
    author: 'JustinBieberVEVO',
    score: 0,
    views: 420000000,
    description: 'Peaches official music video',
    metadata: {
      videoId: 'i0r4M9GDfA4',
      channelId: 'UCIcHI2oV-_7UrrC3yALlppw',
      publishedAt: new Date(Date.now() - 86400000 * 33).toISOString(),
    },
  },
  {
    source: 'youtube',
    sourceId: 'youtube_l_qjSOsS-e4',
    title: 'Circles - Post Malone',
    url: 'https://www.youtube.com/watch?v=l_qjSOsS-e4',
    thumbnail: 'https://i.ytimg.com/vi/l_qjSOsS-e4/default.jpg',
    author: 'Post Malone',
    score: 0,
    views: 1100000000,
    description: 'Circles official music video',
    metadata: {
      videoId: 'l_qjSOsS-e4',
      channelId: 'UCkgsaL9CUH6EMCI78-BkRnw',
      publishedAt: new Date(Date.now() - 86400000 * 34).toISOString(),
    },
  },
  {
    source: 'youtube',
    sourceId: 'youtube_kOHB85vDuow',
    title: 'One Dance - Drake ft. Wizkid & Kyla',
    url: 'https://www.youtube.com/watch?v=kOHB85vDuow',
    thumbnail: 'https://i.ytimg.com/vi/kOHB85vDuow/default.jpg',
    author: 'Drake',
    score: 0,
    views: 1450000000,
    description: 'One Dance official video',
    metadata: {
      videoId: 'kOHB85vDuow',
      channelId: 'UCnkqJVVPtNFb-Ej1RNLTHhw',
      publishedAt: new Date(Date.now() - 86400000 * 35).toISOString(),
    },
  },
  {
    source: 'youtube',
    sourceId: 'youtube_0YMPX7tSS6Q',
    title: 'Hotline Bling - Drake',
    url: 'https://www.youtube.com/watch?v=0YMPX7tSS6Q',
    thumbnail: 'https://i.ytimg.com/vi/0YMPX7tSS6Q/default.jpg',
    author: 'Drake',
    score: 0,
    views: 1830000000,
    description: 'Hotline Bling music video',
    metadata: {
      videoId: '0YMPX7tSS6Q',
      channelId: 'UCnkqJVVPtNFb-Ej1RNLTHhw',
      publishedAt: new Date(Date.now() - 86400000 * 36).toISOString(),
    },
  },
  {
    source: 'youtube',
    sourceId: 'youtube_dFt0AJ1qZ2w',
    title: 'Sunroof - Nicky Youre',
    url: 'https://www.youtube.com/watch?v=dFt0AJ1qZ2w',
    thumbnail: 'https://i.ytimg.com/vi/dFt0AJ1qZ2w/default.jpg',
    author: 'Nicky Youre',
    score: 0,
    views: 890000000,
    description: 'Sunroof official music video',
    metadata: {
      videoId: 'dFt0AJ1qZ2w',
      channelId: 'UCkHHgDe92MKJBxpP6nw7l5Q',
      publishedAt: new Date(Date.now() - 86400000 * 37).toISOString(),
    },
  },
  {
    source: 'youtube',
    sourceId: 'youtube_oofSnsAzIww',
    title: 'Industry Baby - Lil Nas X ft. Jack Harlow',
    url: 'https://www.youtube.com/watch?v=oofSnsAzIww',
    thumbnail: 'https://i.ytimg.com/vi/oofSnsAzIww/default.jpg',
    author: 'Lil Nas X',
    score: 0,
    views: 540000000,
    description: 'Industry Baby official video',
    metadata: {
      videoId: 'oofSnsAzIww',
      channelId: 'UC1tWiPMdbL0kCM8J8kXCJrg',
      publishedAt: new Date(Date.now() - 86400000 * 38).toISOString(),
    },
  },
  {
    source: 'youtube',
    sourceId: 'youtube_xDOy8x9pnVY',
    title: 'Montero - Lil Nas X',
    url: 'https://www.youtube.com/watch?v=xDOy8x9pnVY',
    thumbnail: 'https://i.ytimg.com/vi/xDOy8x9pnVY/default.jpg',
    author: 'Lil Nas X',
    score: 0,
    views: 720000000,
    description: 'Montero official video',
    metadata: {
      videoId: 'xDOy8x9pnVY',
      channelId: 'UC1tWiPMdbL0kCM8J8kXCJrg',
      publishedAt: new Date(Date.now() - 86400000 * 39).toISOString(),
    },
  },
  {
    source: 'youtube',
    sourceId: 'youtube_z7yKhgmlN2s',
    title: 'Break My Soul - Beyonce',
    url: 'https://www.youtube.com/watch?v=z7yKhgmlN2s',
    thumbnail: 'https://i.ytimg.com/vi/z7yKhgmlN2s/default.jpg',
    author: 'Beyonce',
    score: 0,
    views: 280000000,
    description: 'Break My Soul official video',
    metadata: {
      videoId: 'z7yKhgmlN2s',
      channelId: 'UCAHj_mJZLOnkAvwiUji_h7w',
      publishedAt: new Date(Date.now() - 86400000 * 40).toISOString(),
    },
  },
  {
    source: 'youtube',
    sourceId: 'youtube_D_1Wp9jm6vk',
    title: 'Halo - Beyonce',
    url: 'https://www.youtube.com/watch?v=D_1Wp9jm6vk',
    thumbnail: 'https://i.ytimg.com/vi/D_1Wp9jm6vk/default.jpg',
    author: 'Beyonce',
    score: 0,
    views: 970000000,
    description: 'Halo official music video',
    metadata: {
      videoId: 'D_1Wp9jm6vk',
      channelId: 'UCAHj_mJZLOnkAvwiUji_h7w',
      publishedAt: new Date(Date.now() - 86400000 * 41).toISOString(),
    },
  },
  {
    source: 'youtube',
    sourceId: 'youtube_xjjgLqI69QA',
    title: 'Billie Eilish - when we all fall asleep where do we go',
    url: 'https://www.youtube.com/watch?v=xjjgLqI69QA',
    thumbnail: 'https://i.ytimg.com/vi/xjjgLqI69QA/default.jpg',
    author: 'Billie Eilish',
    score: 0,
    views: 680000000,
    description: 'when we all fall asleep where do we go',
    metadata: {
      videoId: 'xjjgLqI69QA',
      channelId: 'UCU8aL_V9d6d-2Tx3ng5OeJA',
      publishedAt: new Date(Date.now() - 86400000 * 42).toISOString(),
    },
  },
  {
    source: 'youtube',
    sourceId: 'youtube_ZXzruqA9gxU',
    title: 'Happier Than Ever - Billie Eilish',
    url: 'https://www.youtube.com/watch?v=ZXzruqA9gxU',
    thumbnail: 'https://i.ytimg.com/vi/ZXzruqA9gxU/default.jpg',
    author: 'Billie Eilish',
    score: 0,
    views: 450000000,
    description: 'Happier Than Ever official video',
    metadata: {
      videoId: 'ZXzruqA9gxU',
      channelId: 'UCU8aL_V9d6d-2Tx3ng5OeJA',
      publishedAt: new Date(Date.now() - 86400000 * 43).toISOString(),
    },
  },
  {
    source: 'youtube',
    sourceId: 'youtube_pFTFkqD0S9o',
    title: 'Flowers - Miley Cyrus',
    url: 'https://www.youtube.com/watch?v=pFTFkqD0S9o',
    thumbnail: 'https://i.ytimg.com/vi/pFTFkqD0S9o/default.jpg',
    author: 'Miley Cyrus',
    score: 0,
    views: 350000000,
    description: 'Flowers official music video',
    metadata: {
      videoId: 'pFTFkqD0S9o',
      channelId: 'UCwVJN68ndKDgHNI2BVvI5vg',
      publishedAt: new Date(Date.now() - 86400000 * 44).toISOString(),
    },
  },
  {
    source: 'youtube',
    sourceId: 'youtube_t6rYhC4V1HE',
    title: 'Wrecking Ball - Miley Cyrus',
    url: 'https://www.youtube.com/watch?v=t6rYhC4V1HE',
    thumbnail: 'https://i.ytimg.com/vi/t6rYhC4V1HE/default.jpg',
    author: 'Miley Cyrus',
    score: 0,
    views: 1600000000,
    description: 'Wrecking Ball official video',
    metadata: {
      videoId: 't6rYhC4V1HE',
      channelId: 'UCwVJN68ndKDgHNI2BVvI5vg',
      publishedAt: new Date(Date.now() - 86400000 * 45).toISOString(),
    },
  },
  {
    source: 'youtube',
    sourceId: 'youtube_lfBHV-6haWc',
    title: 'One Kiss - Calvin Harris & Dua Lipa',
    url: 'https://www.youtube.com/watch?v=lfBHV-6haWc',
    thumbnail: 'https://i.ytimg.com/vi/lfBHV-6haWc/default.jpg',
    author: 'Calvin Harris',
    score: 0,
    views: 850000000,
    description: 'One Kiss official video',
    metadata: {
      videoId: 'lfBHV-6haWc',
      channelId: 'UCQNVZMOlz0VYH6MJCJnrwog',
      publishedAt: new Date(Date.now() - 86400000 * 46).toISOString(),
    },
  },
  {
    source: 'youtube',
    sourceId: 'youtube_aOcwNGeD6rY',
    title: 'Unstoppable - Sia',
    url: 'https://www.youtube.com/watch?v=aOcwNGeD6rY',
    thumbnail: 'https://i.ytimg.com/vi/aOcwNGeD6rY/default.jpg',
    author: 'Sia',
    score: 0,
    views: 620000000,
    description: 'Unstoppable official video',
    metadata: {
      videoId: 'aOcwNGeD6rY',
      channelId: 'UCt_VZvC5YN5rPj1Y0o-Hshw',
      publishedAt: new Date(Date.now() - 86400000 * 47).toISOString(),
    },
  },
  {
    source: 'youtube',
    sourceId: 'youtube_1jc61gPjGpg',
    title: 'Chandelier - Sia',
    url: 'https://www.youtube.com/watch?v=1jc61gPjGpg',
    thumbnail: 'https://i.ytimg.com/vi/1jc61gPjGpg/default.jpg',
    author: 'Sia',
    score: 0,
    views: 1350000000,
    description: 'Chandelier official music video',
    metadata: {
      videoId: '1jc61gPjGpg',
      channelId: 'UCt_VZvC5YN5rPj1Y0o-Hshw',
      publishedAt: new Date(Date.now() - 86400000 * 48).toISOString(),
    },
  },
  {
    source: 'youtube',
    sourceId: 'youtube_PsO6ZnUZI0g',
    title: 'Believer - Imagine Dragons',
    url: 'https://www.youtube.com/watch?v=PsO6ZnUZI0g',
    thumbnail: 'https://i.ytimg.com/vi/PsO6ZnUZI0g/default.jpg',
    author: 'Imagine Dragons',
    score: 0,
    views: 1850000000,
    description: 'Believer official music video',
    metadata: {
      videoId: 'PsO6ZnUZI0g',
      channelId: 'UC0M-4uWVpfPAy6JeH7qNVew',
      publishedAt: new Date(Date.now() - 86400000 * 49).toISOString(),
    },
  },
  {
    source: 'youtube',
    sourceId: 'youtube_xAoG9B4V0rE',
    title: 'Radioactive - Imagine Dragons',
    url: 'https://www.youtube.com/watch?v=xAoG9B4V0rE',
    thumbnail: 'https://i.ytimg.com/vi/xAoG9B4V0rE/default.jpg',
    author: 'Imagine Dragons',
    score: 0,
    views: 1950000000,
    description: 'Radioactive official video',
    metadata: {
      videoId: 'xAoG9B4V0rE',
      channelId: 'UC0M-4uWVpfPAy6JeH7qNVew',
      publishedAt: new Date(Date.now() - 86400000 * 50).toISOString(),
    },
  },
];

/**
 * Fetch YouTube Shorts using YouTube Data API
 * Requires YOUTUBE_API_KEY env variable
 * @param {number} maxResults - max videos to fetch
 * @returns {Promise<Array>} Array of video objects
 */
async function fetchYouTubeShorts(maxResults = 25) {
  const apiKey = process.env.YOUTUBE_API_KEY;

  if (!apiKey) {
    console.warn('⚠ YOUTUBE_API_KEY not set. Using mock YouTube data for development');
    return MOCK_YOUTUBE_SHORTS.slice(0, maxResults);
  }

  try {
    const url = 'https://www.googleapis.com/youtube/v3/search';
    const response = await axios.get(url, {
      params: {
        q: 'shorts',
        part: 'snippet',
        maxResults: maxResults,
        type: 'video',
        videoDuration: 'short',
        key: apiKey,
        order: 'relevance',
      },
      timeout: 10000,
    });

    const videos = response.data.items.map((item) => {
      return {
        source: 'youtube',
        sourceId: `youtube_${item.id.videoId}`,
        title: item.snippet.title,
        url: `https://www.youtube.com/watch?v=${item.id.videoId}`,
        thumbnail: item.snippet.thumbnails.medium.url,
        author: item.snippet.channelTitle,
        score: 0,
        description: item.snippet.description,
        metadata: {
          videoId: item.id.videoId,
          channelId: item.snippet.channelId,
          publishedAt: item.snippet.publishedAt,
        },
      };
    });

    console.log(`✓ Fetched ${videos.length} YouTube Shorts`);
    return videos;
  } catch (err) {
    console.error('✗ YouTube fetch error:', err.message);
    // Return mock data as fallback
    console.log('⚠ Using mock YouTube data (API key might be invalid)');
    return MOCK_YOUTUBE_SHORTS.slice(0, maxResults);
  }
}

module.exports = { fetchYouTubeShorts };
